[build-system]
requires = ['setuptools',
            'setuptools_scm',
            'wheel',
            'cython>=0.29.22',
            'oldest-supported-numpy']
build-backend = 'setuptools.build_meta'
